name: front-end unit-test
on: [pull_request]
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm i
        working-directory: frontend/
      - run: npx jest src/components/
        working-directory: frontend/
